# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   build:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4

#     - name: Install prerequisites (curl and wget)
#       run: apt-get update && apt-get install -y curl wget

#     - name: Setup .NET
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: '8.x' # version is 8.0

#     - name: Install dependencies
#       run: dotnet restore ./singleSolution.sln

#     - name: Build
#       run: dotnet build --configuration Release ./singleSolution.sln

#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: lts/*

#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps

#     - name: Run Playwright tests
#       run: npx playwright test

#     - name: Run .NET tests
#       run: dotnet test --no-build --configuration Release ./singleSolution.sln

#     - uses: actions/upload-artifact@v4
#       if: always()
#       with:
#         name: test-results
#         path: |
#           playwright-report/
#           **/TestResults/
#         retention-days: 30
